/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/google-login": {
    /** Google Login */
    post: operations["google_login_api_google_login_post"];
  };
  "/api/register": {
    /** Register */
    post: operations["register_api_register_post"];
  };
  "/api/register/": {
    /** Register */
    post: operations["register_api_register__post"];
  };
  "/api/login": {
    /** Login */
    post: operations["login_api_login_post"];
  };
  "/api/login/": {
    /** Login */
    post: operations["login_api_login__post"];
  };
  "/api/verify-token": {
    /** Verify Auth Token */
    get: operations["verify_auth_token_api_verify_token_get"];
  };
  "/api/verify-token/": {
    /** Verify Auth Token */
    get: operations["verify_auth_token_api_verify_token__get"];
  };
  "/api/games/": {
    /** Create Game */
    post: operations["create_game_api_games__post"];
  };
  "/api/games/{user_id}/{game_id}": {
    /** Get Game */
    get: operations["get_game_api_games__user_id___game_id__get"];
    /** Delete Game */
    delete: operations["delete_game_api_games__user_id___game_id__delete"];
  };
  "/api/games/{user_id}/{game_id}/": {
    /** Get Game */
    get: operations["get_game_api_games__user_id___game_id___get"];
    /** Delete Game */
    delete: operations["delete_game_api_games__user_id___game_id___delete"];
  };
  "/api/games/all": {
    /** Get All Games */
    get: operations["get_all_games_api_games_all_get"];
  };
  "/api/games/all/": {
    /** Get All Games */
    get: operations["get_all_games_api_games_all__get"];
  };
  "/api/games/user/{user_id}": {
    /** Get User Games */
    get: operations["get_user_games_api_games_user__user_id__get"];
  };
  "/api/games/user/{user_id}/": {
    /** Get User Games */
    get: operations["get_user_games_api_games_user__user_id___get"];
  };
  "/api/games/{game_id}": {
    /** Get Game By Id */
    get: operations["get_game_by_id_api_games__game_id__get"];
    /** Update Game */
    put: operations["update_game_api_games__game_id__put"];
  };
  "/api/games/{game_id}/": {
    /** Get Game By Id */
    get: operations["get_game_by_id_api_games__game_id___get"];
    /** Update Game */
    put: operations["update_game_api_games__game_id___put"];
  };
  "/api/games/{game_id}/history": {
    /** Get Game History */
    get: operations["get_game_history_api_games__game_id__history_get"];
  };
  "/api/games/{game_id}/history/": {
    /** Get Game History */
    get: operations["get_game_history_api_games__game_id__history__get"];
  };
  "/api/games/{game_id}/revert": {
    /** Revert Game */
    post: operations["revert_game_api_games__game_id__revert_post"];
  };
  "/api/games/{game_id}/revert/": {
    /** Revert Game */
    post: operations["revert_game_api_games__game_id__revert__post"];
  };
  "/api/games/files/{game_id}/": {
    /** Get Game Files */
    get: operations["get_game_files_api_games_files__game_id___get"];
  };
  "/api/games/files/{game_id}": {
    /** Update Game File */
    post: operations["update_game_file_api_games_files__game_id__post"];
  };
  "/api/games/files/{game_id}/download": {
    /** Download Game */
    get: operations["download_game_api_games_files__game_id__download_get"];
  };
  "/api/games/deploy/{game_id}": {
    /** Deploy Game */
    post: operations["deploy_game_api_games_deploy__game_id__post"];
  };
  "/api/games/deploy/{game_id}/": {
    /** Deploy Game */
    post: operations["deploy_game_api_games_deploy__game_id___post"];
  };
  "/api/games/deploy/{game_id}/history": {
    /** Get Game History */
    get: operations["get_game_history_api_games_deploy__game_id__history_get"];
  };
  "/api/games/deploy/{game_id}/history/": {
    /** Get Game History */
    get: operations["get_game_history_api_games_deploy__game_id__history__get"];
  };
  "/api/enhance-prompt": {
    /** Enhance Prompt */
    post: operations["enhance_prompt_api_enhance_prompt_post"];
  };
  "/api/assets/sound": {
    /**
     * Generate Sound
     * @description Generate a sound effect
     */
    post: operations["generate_sound_api_assets_sound_post"];
  };
  "/api/assets/sound/": {
    /**
     * Generate Sound
     * @description Generate a sound effect
     */
    post: operations["generate_sound_api_assets_sound__post"];
  };
  "/api/assets/image": {
    /**
     * Generate Image
     * @description Generate a game image
     */
    post: operations["generate_image_api_assets_image_post"];
  };
  "/api/assets/image/": {
    /**
     * Generate Image
     * @description Generate a game image
     */
    post: operations["generate_image_api_assets_image__post"];
  };
  "/api/check-errors": {
    /** Check Errors */
    post: operations["check_errors_api_check_errors_post"];
  };
  "/api/check-errors/": {
    /** Check Errors */
    post: operations["check_errors_api_check_errors__post"];
  };
  "/": {
    /** Read Root */
    get: operations["read_root__get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** AssetRequest */
    AssetRequest: {
      /** Description */
      description: string;
      /**
       * Type
       * @default single
       */
      type?: string;
      /** Game Type */
      game_type?: string | null;
      /**
       * Size
       * @default 1024x1024
       */
      size?: string;
    };
    /** EnhancePromptRequest */
    EnhancePromptRequest: {
      /** Prompt */
      prompt: string;
      /** Example */
      example: string;
    };
    /** EnhancePromptResponse */
    EnhancePromptResponse: {
      /** Enhancedprompt */
      enhancedPrompt: string;
    };
    /** ErrorCheckRequest */
    ErrorCheckRequest: {
      /** Gameid */
      gameId: string;
    };
    /** Game */
    Game: {
      /** Name */
      name: string;
      /** User Id */
      user_id: string;
      /** Folder Path */
      folder_path: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** User */
    User: {
      /** Email */
      email: string;
      /** Password */
      password: string;
      /** Name */
      name?: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Google Login */
  google_login_api_google_login_post: {
    requestBody: {
      content: {
        "application/json": Record<string, never>;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Register */
  register_api_register_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["User"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Register */
  register_api_register__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["User"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Login */
  login_api_login_post: {
    requestBody: {
      content: {
        "application/json": Record<string, never>;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Login */
  login_api_login__post: {
    requestBody: {
      content: {
        "application/json": Record<string, never>;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Verify Auth Token */
  verify_auth_token_api_verify_token_get: {
    parameters: {
      header?: {
        authorization?: string;
        Cookie?: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Verify Auth Token */
  verify_auth_token_api_verify_token__get: {
    parameters: {
      header?: {
        authorization?: string;
        Cookie?: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Game */
  create_game_api_games__post: {
    parameters: {
      header?: {
        authorization?: string;
        Cookie?: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Game"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Game */
  get_game_api_games__user_id___game_id__get: {
    parameters: {
      header?: {
        authorization?: string;
        Cookie?: string;
      };
      path: {
        user_id: string;
        game_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Game */
  delete_game_api_games__user_id___game_id__delete: {
    parameters: {
      header?: {
        authorization?: string;
        Cookie?: string;
      };
      path: {
        user_id: string;
        game_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Game */
  get_game_api_games__user_id___game_id___get: {
    parameters: {
      header?: {
        authorization?: string;
        Cookie?: string;
      };
      path: {
        user_id: string;
        game_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Game */
  delete_game_api_games__user_id___game_id___delete: {
    parameters: {
      header?: {
        authorization?: string;
        Cookie?: string;
      };
      path: {
        user_id: string;
        game_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get All Games */
  get_all_games_api_games_all_get: {
    parameters: {
      header?: {
        authorization?: string;
        Cookie?: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get All Games */
  get_all_games_api_games_all__get: {
    parameters: {
      header?: {
        authorization?: string;
        Cookie?: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get User Games */
  get_user_games_api_games_user__user_id__get: {
    parameters: {
      header?: {
        authorization?: string;
        Cookie?: string;
      };
      path: {
        user_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get User Games */
  get_user_games_api_games_user__user_id___get: {
    parameters: {
      header?: {
        authorization?: string;
        Cookie?: string;
      };
      path: {
        user_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Game By Id */
  get_game_by_id_api_games__game_id__get: {
    parameters: {
      header?: {
        authorization?: string;
        Cookie?: string;
      };
      path: {
        game_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Game */
  update_game_api_games__game_id__put: {
    parameters: {
      header?: {
        authorization?: string;
        Cookie?: string;
      };
      path: {
        game_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Game"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Game By Id */
  get_game_by_id_api_games__game_id___get: {
    parameters: {
      header?: {
        authorization?: string;
        Cookie?: string;
      };
      path: {
        game_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Game */
  update_game_api_games__game_id___put: {
    parameters: {
      header?: {
        authorization?: string;
        Cookie?: string;
      };
      path: {
        game_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Game"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Game History */
  get_game_history_api_games__game_id__history_get: {
    parameters: {
      header?: {
        authorization?: string;
        Cookie?: string;
      };
      path: {
        game_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Game History */
  get_game_history_api_games__game_id__history__get: {
    parameters: {
      header?: {
        authorization?: string;
        Cookie?: string;
      };
      path: {
        game_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Revert Game */
  revert_game_api_games__game_id__revert_post: {
    parameters: {
      header?: {
        authorization?: string;
        Cookie?: string;
      };
      path: {
        game_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": Record<string, never>;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Revert Game */
  revert_game_api_games__game_id__revert__post: {
    parameters: {
      header?: {
        authorization?: string;
        Cookie?: string;
      };
      path: {
        game_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": Record<string, never>;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Game Files */
  get_game_files_api_games_files__game_id___get: {
    parameters: {
      header?: {
        authorization?: string;
        Cookie?: string;
      };
      path: {
        game_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Game File */
  update_game_file_api_games_files__game_id__post: {
    parameters: {
      header?: {
        authorization?: string;
        Cookie?: string;
      };
      path: {
        game_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": Record<string, never>;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Download Game */
  download_game_api_games_files__game_id__download_get: {
    parameters: {
      header?: {
        authorization?: string;
        Cookie?: string;
      };
      path: {
        game_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Deploy Game */
  deploy_game_api_games_deploy__game_id__post: {
    parameters: {
      header?: {
        authorization?: string;
        Cookie?: string;
      };
      path: {
        game_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Deploy Game */
  deploy_game_api_games_deploy__game_id___post: {
    parameters: {
      header?: {
        authorization?: string;
        Cookie?: string;
      };
      path: {
        game_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Game History */
  get_game_history_api_games_deploy__game_id__history_get: {
    parameters: {
      header?: {
        authorization?: string;
        Cookie?: string;
      };
      path: {
        game_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Game History */
  get_game_history_api_games_deploy__game_id__history__get: {
    parameters: {
      header?: {
        authorization?: string;
        Cookie?: string;
      };
      path: {
        game_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Enhance Prompt */
  enhance_prompt_api_enhance_prompt_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["EnhancePromptRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["EnhancePromptResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Generate Sound
   * @description Generate a sound effect
   */
  generate_sound_api_assets_sound_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AssetRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Generate Sound
   * @description Generate a sound effect
   */
  generate_sound_api_assets_sound__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AssetRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Generate Image
   * @description Generate a game image
   */
  generate_image_api_assets_image_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AssetRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Generate Image
   * @description Generate a game image
   */
  generate_image_api_assets_image__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AssetRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Check Errors */
  check_errors_api_check_errors_post: {
    parameters: {
      header?: {
        authorization?: string;
        Cookie?: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ErrorCheckRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Check Errors */
  check_errors_api_check_errors__post: {
    parameters: {
      header?: {
        authorization?: string;
        Cookie?: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ErrorCheckRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Read Root */
  read_root__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}
